class Caotral::Linker::ELF::Section::Rel
  def initialize: (?addend: bool) -> void
  def set!: (
    ?offset: Integer?,
    ?info: Integer?,
    ?addend: Integer?
  ) -> self
  def build: () -> String
  def offset: () -> Integer
  def info: () -> Integer
  def addend: () -> Integer
end
