class Caotral::Linker::ELF::Section::Symtab
  attr_accessor name_string: String

  def initialize: (?opts: untyped) -> void
  def set!: (
    ?name: Integer?,
    ?info: Integer?,
    ?other: Integer?,
    ?shndx: Integer?,
    ?value: Integer?,
    ?size: Integer?
  ) -> self
  def name_offset: () -> Integer
end
