class Vaporware::Compiler::Assembler::ELF::Section::Note
  def self.gnu_property: () -> String

  @nsize: Array[Integer]?
  @dsize: Array[Integer]?
  @type: Array[Integer]?
  @name: Array[Integer]?
  @desc: Array[Integer]?

  def initialize: (?type: String | Symbol) -> void

  def set!: (
    ?nsize: Integer?,
    ?dsize: Integer?,
    ?type: Integer?,
    ?name: (Integer | Array[Integer] | String)?,
    ?desc: (Integer | Array[Integer] | String)?
  ) -> self
  def gnu_property!: () -> void
  def build: () -> String

  private
  def name!: ((Integer | Array[Integer] | String)?) -> Array[Integer]
  def desc!: ((String | Array[Integer])?) -> Array[Integer]
  def bytes: () -> Array[Array[Integer] | nil]
  def align!: (Array[Integer], Integer) -> Array[Integer]
  def num2bytes: (Integer?, Integer) -> Array[Integer]
  def check: ((Integer | Array[Integer])?, Integer) -> bool
end
