class Vaporware::Compiler
  GCC_LD_PATH: String
  LD_PATH: String
  DYN_LD_PATH: String
  SHARED_LD_PATH: String
  # class methods
  def self.compile!: (input: String, ?output: String, ?compiler_options: Array[String], ?debug: bool, ?shared: bool) -> void
  def initialize: (input: String, output: String, ?debug: bool, ?shared: bool) -> void

  def compile: (compiler_options: Array[String]) -> String
end
