use Vaporware::Compiler::Assembler::ELF::Header
use Vaporware::Compiler::Assembler::ELF::Sections
use Vaporware::Compiler::Assembler::ELF::Section::Text

class Vaporware::Compiler::Assembler
  @input: String
  @output: String
  @assembler: String
  @elf_header: Header
  @sections: Sections
  @debug: bool

  def initialize: (input: String, ?output: String, ?type: Symbol, ?debug: bool) -> void
  def assemble: (?assembler: String, ?assembler_options: Array[String] | [], ?input: String, ?output: String, ?debug: bool) -> String
  def obj_file: () -> String
  def to_elf: (?input: String, ?output: String, ?debug: bool) -> void
  def read: (?input: String, ?text: Text) -> void
end
