use Vaporware::Compiler::Assembler::ELF

class Vaporware::Compiler::Assembler::ELF::SectionHeader
  @name: Array[Integer]?
  @type: Array[Integer]?
  @flags: Array[Integer]?
  @addr: Array[Integer]?
  @offset: Array[Integer]?
  @size: Array[Integer]?
  @link: Array[Integer]?
  @info: Array[Integer]?
  @addralign: Array[Integer]?
  @entsize: Array[Integer]?

  def build: () -> String
  def set!: (?name: Integer?, ?type: Integer?, ?flags: Integer?, ?addr: Integer?, ?offset: Integer?, ?size: Integer?, ?link: Integer?, ?info: Integer?, ?addralign: Integer?, ?entsize: Integer?) -> Vaporware::Compiler::Assembler::ELF::SectionHeader
  def null!: () -> ELF::SectionHeader
  def text!: () -> ELF::SectionHeader
  def note!: () -> ELF::SectionHeader

  private def bytes: () -> Array[Array[Integer]?]
  private def check: ((Array[Integer] | Integer)?, Integer) -> bool
  private def num2bytes: (Integer?, Integer) -> Array[Integer]
end
