class Caotral::Assembler
  @input: String
  @output: String
  @assembler: String
  @asm_reader: Caotral::Assembler::Reader
  @debug: bool

  def initialize: (input: String, ?output: String, ?assembler: String, ?type: Symbol, ?debug: bool) -> void
  def assemble: (?assembler: String, ?assembler_options: Array[String] | [], ?input: String, ?output: String, ?debug: bool, ?shared: bool) -> String
  def obj_file: () -> String
  def to_elf: (?input: String, ?output: String, ?debug: bool) -> String
end
