class Caotral::Linker::Finalizer
  @elf: Caotral::Binary::ELF
  @metadata: Hash[Symbol, untyped]
  @shared: bool
  @executable: bool
  @pie: bool

  def initialize: (elf: Caotral::Binary::ELF, metadata: Hash[Symbol, untyped], shared: bool, executable: bool, pie: bool, debug: bool) -> void
  def apply!: () -> Caotral::Binary::ELF
end
