class Caotral::Linker::Reader
  def self.read!: (input: String, ?debug: bool, ?linker_options: Array[String]) -> Caotral::Binary::ELF
  def initialize: (input: String, ?debug: bool, ?linker_options: Array[String]) -> void
  def read: () -> Caotral::Binary::ELF
end
