class Caotral::Assembler::ELF::Section::BSS
  attr_reader size: Integer
  attr_reader offset: Integer

  def build: () -> String
  def set!: () -> self

  private
  def bytes: () -> Array[Array[Integer?]]
  def check: (Integer, Integer) -> bool
end
