class Caotral::Compiler::Analyzer
  @ast: RubyVM::AbstractSyntaxTree::Node
  @context: Caotral::Compiler::Context

  def self.analyze: (
    RubyVM::AbstractSyntaxTree::Node ast,
    ?Caotral::Compiler::Context context
  ) -> Caotral::Compiler::Context

  def initialize: (
    RubyVM::AbstractSyntaxTree::Node ast,
    Caotral::Compiler::Context context
  ) -> void

  def analyze: () -> Caotral::Compiler::Context

  private

  def register_entry: (RubyVM::AbstractSyntaxTree::Node scope) -> void
  def register_variables_and_methods: (RubyVM::AbstractSyntaxTree::Node? node) -> void
  def analyze_function_scope: (RubyVM::AbstractSyntaxTree::Node node) -> {
    name: Symbol,
    parameters: Array[Symbol],
    locals: Array[Symbol],
    body: RubyVM::AbstractSyntaxTree::Node
  }
end
