class Caotral::Compiler::Generator
  REGISTER: Array[String]

  attr_accessor main: bool
  attr_reader precompile: String
  attr_reader shared: bool

  @main: bool
  @debug: bool
  @doned: Set[Symbol]
  @defined_methods: Set[Symbol]
  @defined_variables: Set[Symbol]
  @emitter: Caotral::Compiler::Emitter
  @precompile: String
  @seq: Integer
  @shared: bool
  @ast: RubyVM::AbstractSyntaxTree::Node
  @source: String

  # class methods
  def initialize: (input: String, ?output: String, ?debug: bool, ?shared: bool) -> void

  # instance private methods
  def already_build_methods?: -> bool
  def call_method: (RubyVM::AbstractSyntaxTree::Node, bool) -> void
  def comp: (String) -> void
  def compile: () -> void
  def compile_shared_option: () -> Array[String]
  def define_method_prologue: (RubyVM::AbstractSyntaxTree::Node) -> void
  def epilogue: () -> void
  def lvar: (Symbol) -> void
  def lvar_offset: (Symbol | nil) -> Integer
  def method: (Symbol, RubyVM::AbstractSyntaxTree::Node) -> void
  def prologue_methods: () -> void
  def register_var_and_method: (RubyVM::AbstractSyntaxTree::Node?) -> void
  def ret: () -> void
  def to_asm: (RubyVM::AbstractSyntaxTree::Node?, ?bool) -> void

  private

  def instruction: (String, *(String | Symbol | Integer)) -> void
  def label: (String | Symbol) -> void
  def directive: (String) -> void
end
