class Caotral::Compiler::Linker
  @inputs: Array[String]
  @output: String
  @linker: String
  @options: Array[String]
  @shared: bool
  @debug: bool

  def initialize: (inputs: Array[String], ?output: String, ?linker: String, ?linker_options: Array[String], ?shared: bool, ?debug: bool) -> void
  def link: (inputs: Array[String], ?output: String, ?shared: bool, ?debug: bool) -> void

  def link_command: () -> String
  def libpath: () -> String
  def gcc_libpath: () -> String
end
