class Vaporware::Assembler::ELF::Section::Symtab
  @name: Array[Integer]?
  @info: Array[Integer]
  @other: Array[Integer]
  @shndx: Array[Integer]
  @value: Array[Integer]
  @size: Array[Integer]

  def initialize: () -> void
  def set!: (?name: Integer?, ?info: Integer?, ?other: Integer?, ?shndx: Integer?, ?value: Integer?, ?size: Integer?) -> void
  def build: () -> String

  private def name!: (String) -> void
  private def desc!: (String) -> void
  private def bytes: () -> Array[Array[Integer]?]
  private def align!: (Array[Integer], Integer) -> void
  private def num2bytes: (Integer?, Integer) -> Array[Integer]
  private def check: ((String | Integer | Array[Integer])?, Integer) -> bool
  private def name2bytes: ((String | Integer | Array[Integer])?, Integer) -> Array[Integer]?
end
