class Vaporware::Assembler::ELF::Section::Text
  PREFIX: Hash[Symbol, Integer]
  REGISTER_CODE: Hash[Symbol, Integer]
  OPECODE: Hash[Symbol, Array[Integer]]

  @bytes: Array[untyped]
  @lines: Array[String]
  @label_positions: Hash[String, Integer]

  attr_reader offset: Integer

  def initialize: () -> void
  def assemble!: (String) -> void
  def align: (untyped, Integer) -> untyped
  def build: () -> String

  private

  def opecode: ((String | Symbol)?, Integer, *String) -> Array[Integer]
  def mov: ((String | Symbol), *String) -> Array[Integer]
  def calc: ((String | Symbol), *String) -> Array[Integer]
  def jump: ((String | Symbol), Integer, *String) -> Array[Integer]
  def push: (*String) -> Array[Integer]
  def pop: (*String) -> Array[Integer]
  def cmp: ((String | Symbol), *String) -> Array[Integer]
  def reg: ((String | Symbol)) -> Integer
  def sete: ((String | Symbol), *String) -> Array[Integer]
  def immediate: (String) -> Array[(Integer | Float | String)?]
end
