#!/usr/bin/env ruby

require "vaporware"
require "optparse"
opt = OptionParser.new
options = {
  compile: true,
  assembly: true,
  link: true,
}

subcommands = Hash.new do |hash, key|
  $stderr.puts "no such subcommand: #{key}"
  exit 1
end

subcommands["compile"] = OptionParser.new do |opt|
  opt.on("-o", "--output=FILE", "Output file name") { |v| options[:output] = v }
  opt.on("-c", "--assembly-only", "Assembly only, do not link") { options[:link] = false }
  opt.on("-S", "--compile-only", "Compile only, do not assemble") do
    options[:assembly] = false
    options[:link] = false
  end
  opt.on("-a", "--assembler=ASSEMBLER", "Specify the assembler to use (e.g., as, gas)") { |v| options[:assembler] = v }
  opt.on("-l", "--linker=LINKER", "Specify the linker to use (e.g., gold, lld, mold)") { |v| options[:linker] = v }

  opt.on("-s", "--shared", "Compile as shared object") { options[:shared] = true }
  opt.on("-d", "--debug", "Compile with debug information") { options[:debug] = true }
end

subcommands["assemble"] = OptionParser.new do |opt|
  opt.on("-o", "--output=FILE", "Output file name") { |v| options[:output] = v }
  opt.on("-a", "--assembler=ASSEMBLER", "Specify the assembler to use (e.g., as, gas)") { |v| options[:assembler] = v }

  opt.on("-s", "--shared", "Compile as shared object") { options[:shared] = true }
  opt.on("-d", "--debug", "Compile with debug information") { options[:debug] = true }
end

subcommands["link"] = OptionParser.new do |opt|
  opt.on("-o", "--output=FILE", "Output file name") { |v| options[:output] = v }
  opt.on("-l", "--linker=LINKER", "Specify the linker to use (e.g., gold, lld, mold)") { |v| options[:linker] = v }

  opt.on("-s", "--shared", "Compile as shared object") { options[:shared] = true }
  opt.on("-d", "--debug", "Compile with debug information") { options[:debug] = true }
end

begin
  subcommands[ARGV.shift].parse!(ARGV) if ARGV.any?
  raise "please compile target file" if ARGV.empty?
rescue => e
  STDERR.puts(e.message)
  exit 1
end

assembler, linker = nil, nil
assembler = options[:assembler] || "self" 
linker = options[:linker] || "mold"
debug = options[:debug] || false
output = options[:output] || "a.out"
input = ARGV.first
shared = options[:shared] || false

if File.extname(input) == ".s"
  options[:assembly] = true
  options[:compile] = false
end

basename = File.expand_path(File.basename(input, ".*"))
extname = File.extname(output) == ".so"

output = basename + ".s"
Vaporware.compile(input:, output:, debug:) if options[:compile]
input, output = output, basename + ".o"
if options[:assembly]
  Vaporware.assemble(input:, output:, assembler:, debug:)
  File.delete(input) if File.exist?(input) && !debug
end
if options[:link]
  input, output = output, basename
  output = options[:output] || output
  output += ".so" if options[:shared] && !extname
  Vaporware.link(input:, output:, debug:, shared:, linker:) if options[:link]
  File.delete(input) if File.exist?(input) && !debug
end
