class Caotral::Assembler::ELF::SectionHeader < Caotral::Binary::ELF::SectionHeader
  def null!: () -> Caotral::Assembler::ELF::SectionHeader
  def text!: () -> Caotral::Assembler::ELF::SectionHeader
  def data!: () -> Caotral::Assembler::ELF::SectionHeader
  def bss!: () -> Caotral::Assembler::ELF::SectionHeader
  def note!: () -> Caotral::Assembler::ELF::SectionHeader
  def symtab!: () -> Caotral::Assembler::ELF::SectionHeader
  def strtab!: () -> Caotral::Assembler::ELF::SectionHeader
  def shstrtab!: () -> Caotral::Assembler::ELF::SectionHeader
end
