use Caotral::Assembler::ELF::Error

module Caotral::Assembler::ELF::Utils
  def build: () -> String
  def size: () -> Integer
  def empties: () -> Array[Symbol]
  private def align: (Array[Integer], Integer) -> void
  private def check: ((Array[Integer] | Integer)?, Integer) -> bool
  private def num2bytes: (Integer, Integer) -> Array[Integer]
  private def bytes: () -> Array[Array[Integer]?]
  private def hexas: (Integer, Integer) -> Array[Integer]
  private def must_be_filled_section_fields: () -> Array[Symbol]
end
