use Vaporware::Assembler::ELF::Section

class Vaporware::Assembler::ELF::Sections
  ATTRIBUTES: Array[Symbol]
  attr_reader null: Section
  attr_reader text: Section
  attr_reader data: Section
  attr_reader bss: Section
  attr_reader note: Section
  attr_reader symtab: Section
  attr_reader strtab: Section
  attr_reader shstrtab: Section

  def initialize: () -> void
  def each: (){ (Vaporware::Assembler::ELF::Section) -> void } -> void
end
